---
- name: "breaking-change"
  color: ee0701
  description: "A breaking change for existing users."
- name: "bug"
  color: ee0701
  description: "Inconsistencies or issues which will cause a problem for users or implementors."
- name: "documentation"
  color: 0052cc
  description: "Solely about the documentation of the project."
- name: "enhancement"
  color: 0052cc
  description: "Enhancement of the code, not introducing new features."
- name: "refactor"
  color: 0052cc
  description: "Improvement of existing code, not introducing new features."
- name: "performance"
  color: 0052cc
  description: "Improving performance, not introducing new features."
- name: "ci"
  color: 0052cc
  description: "Work that improves the general workflow."
- name: "security"
  color: 0052cc
  description: "Marks a security issue that needs to be resolved ASAP."
- name: "new-feature"
  color: 0e8a16
  description: "New features or options."
- name: "maintenance"
  color: 2af79e
  description: "Generic maintenance tasks."
- name: "dependencies"
  color: 2af79e
  description: "Upgrade or downgrade of project dependencies."
- name: "question"
  color: 7ca966
  description: "Further information is requested."
- name: "duplicate"
  color: ee0701
  description: "This issue or pull request already exists."
- name: "in-progress"
  color: fef2c0
  description: "Issue is currently being resolved by a developer."
- name: "stale"
  color: fef2c0
  description: "There has not been activity on this issue or PR for quite some time."
- name: "no-stale"
  color: fef2c0
  description: "This issue or PR is exempted from the stale bot."
- name: "wontfix"
  color: fef2c0
  description: "This will not be worked on."
- name: "incomplete"
  color: ee0701
  description: "Marks a PR or issue that is missing information."
- name: "beginner-friendly"
  color: 0e8a16
  description: "Good first issue for people wanting to contribute to the project."
- name: "help-wanted"
  color: fef2c0
  description: "We need some extra helping hands or expertise in order to resolve this."
- name: "discussion-needed"
  color: fef2c0
  description: "This should be discussed first before proceeding."
- name: "monitoring"
  color: fef2c0
  description: "This is still being monitored before it can be closed as resolved."
- name: "critical"
  color: ee0701
  description: "This should be dealt with ASAP. Not fixing this issue would be a serious error."
- name: "high"
  color: ee0701
  description: "After critical issues are fixed, these should be dealt with before any further issues."
- name: "medium"
  color: 0e8a16
  description: "This issue may be useful, and needs some attention."
- name: "low"
  color: 0e8a16
  description: "Nice addition, maybe... someday..."
- name: "major"
  color: ee0701
  description: "This issue or PR causes a major version bump in the version number."
- name: "minor"
  color: 0e8a16
  description: "This issue or PR causes a minor version bump in the version number."
- name: "programming"
  color: 2af79e
  description: "This issue is related to programming and code."
- name: "design"
  color: 2af79e
  description: "This issue is related to design, graphics and user interface."
- name: "building"
  color: 2af79e
  description: "This issue is related to modeling and map building."