# Labels for issues and pull-requests.
labels:
  # Statuses
  - name: "status: evaluating"
    color: f0ad3f
    description: "Applied to all new issues & PRs, someone needs to triage this."
  - name: "status: stale"
    color: f0ad3f
    description: "There hasn't been any activity on this for quite some time."
  - name: "status: no-stale"
    color: f0ad3f
    description: "This is exempted from the stale bot."
  ## Awaiting
  - name: "status: blocked"
    color: 3732e4
    description: "This is being blocked by other ongoing issues."
  - name: "status: help-wanted"
    color: 3732e4
    description: "We need some extra helping hands or expertise in order to resolve this."
  - name: "status: discussion-needed"
    color: 3732e4
    description: "This should be discussed first before proceeding."
  ## In-progress
  - name: "status: investigating"
    color: f0ad3f
    description: "This is currently being investigated and looked into."
  ## Rejected
  - name: "status: incomplete"
    color: ee0701
    description: "Marks a PR or issue that is missing information."
  - name: "status: duplicate"
    color: ee0701
    description: "This issue or pull request already exists."
  - name: "status: wontfix"
    color: ee0701
    description: "This won't be worked on."
  ## Completed
  - name: "status: monitoring"
    color: 2af79e
    description: "This is still being monitored before it can be closed as resolved."
  
  # Types
  - name: "type: bug"
    color: 0052cc
    description: "Something isn't working as expected."
  - name: "type: enhancement"
    color: 0052cc
    description: "Enhancement of the code, not introducing new features."
  - name: "type: feature"
    color: 0052cc
    description: "New feature, concept idea or suggestion."
  - name: "type: docs"
    color: 0052cc
    description: "Solely about the documentation of the project."
  - name: "type: dependencies"
    color: 0052cc
    description: "Upgrade or downgrade of project dependencies."
  - name: "type: question"
    color: 0052cc
    description: "Further information is requested for discussion."
  - name: "type: refactor"
    color: 0052cc
    description: "Improvement of existing code."
  - name: "type: performance"
    color: 0052cc
    description: "Improvement of performance."
  - name: "type: workflow"
    color: 0052cc
    description: "Improvement of the general workflow."
  - name: "type: translation"
    color: 0052cc
    description: "Request for better localization."
  - name: "type: maintenance"
    color: 0052cc
    description: "Generic maintenance tasks."

  # Semantic Versioning
  - name: "semver: major"
    color: 98dae3
    description: "This will cause a major bump in the version X.0.0"
  - name: "semver: minor"
    color: 98dae3
    description: "This will cause a minor bump in the version 0.X.0"
  - name: "semver: patch"
    color: 98dae3
    description: "This will cause a patch bump in the version 0.0.X"

  # Priorities
  ## High
  - name: "priority: security"
    color: ee0701
    description: "Marks a security issue that needs to be resolved ASAP."
  - name: "priority: critical"
    color: ee0701
    description: "This should be dealt with first. Not fixing this issue might be a serious error."
  - name: "priority: high"
    color: ee0701
    description: "After critical issues are fixed, these should be dealt with before any further issues."
  ## Low
  - name: "priority: medium"
    color: 0e8a16
    description: "This issue may be useful, and needs some attention."
  - name: "priority: low"
    color: 0e8a16
    description: "Nice addition, maybe... someday..."

  # Featuring
  - name: "feat: breaking-changes"
    color: 71241c
    description: "This might break other parts of the code."

  # Special
  - name: "beginner-friendly"
    color: 0e8a16
    description: "Good first issue for people wanting to contribute to the project."
