name: "Bug Report"
description: "Report any unexpected glitches and inconsistencies."
title: "Summarize your report."
labels: ["status: evaluating, type: bug"]
body:
  - type: markdown
    attributes:
      value: Thank you for trying to report any bugs. Let's fix them together!
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please enter an explicit description of your issue."
      placeholder: "Short and explicit description of your incident..."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction Steps"
      description: "Please tell us exactly how you reproduced it."
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: "Screenshots & Videos"
      description: "If applicable, add any media files to help explain your problem."
      placeholder: "https://imgur.com/a/iceeburr-5LJTfgw"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Please copy and paste any relevant log output or attach an image."
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "Which operating systems are affected?"
      multiple: true
      options:
        - Computer
        - Mobile
        - Controller
        - Other
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: "Additional Information"
      description: "Include any additional information about the issue."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Please try to do all of the checks below."
      options:
        - label: "Reproduced the issue at least once."
          required: true
        - label: "Attached valid error logs."
          required: false
        - label: "Included screenshots of the bug happening."
          required: false