name: 'Close Stale Issue & PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been put on stale due to inactivity.'
          stale-pr-message: 'This PR has been put on stale due to inactivity.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'status: no-stale, status: investigating, status: help-wanted, status: discussion-needed, priority: security, priority: critical'
          exempt-pr-labels: 'status: no-stale, status: investigating, status: help-wanted, status: discussion-needed, priority: security, priority: critical'
          days-before-stale: 14
          days-before-close: 21
          close-issue-reason: 'completed'